name: Node.js CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

env:
  NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Install
        run: npm ci

      - name: Build
        run: npm run build

      - name: Tests
        run: npm test

      - name: Publish
        if: ${{ github.event_name == 'push' && github.ref_name == 'main' }}
        run: npm publish --access public

      - name: Next version
        if: ${{ github.event_name == 'push' && github.ref_name == 'main' }}
        run: npm version patch -m "[skip ci] Prepare version %s"
